# Generated by Django 3.0.2 on 2020-01-21 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('annual_revenue', models.FloatField()),
                ('avg_bank_balance', models.FloatField()),
                ('avg_credit_card_volume', models.FloatField()),
                ('tax_id', models.IntegerField(blank=True)),
                ('phone', models.IntegerField(blank=True)),
                ('naics', models.IntegerField(blank=True)),
                ('has_been_profitable', models.BooleanField()),
                ('bankrupted', models.BooleanField()),
                ('inception_date', models.DateField()),
                ('has_been_updated', models.BooleanField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.FloatField(blank=True)),
                ('credit_history', models.IntegerField(blank=True)),
                ('entity_type', models.CharField(max_length=200)),
                ('filter_id', models.IntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('dob', models.DateTimeField()),
                ('phone', models.IntegerField(blank=True)),
                ('ssn', models.IntegerField(blank=True)),
                ('percent_own', models.FloatField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Address')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='owners',
            field=models.ManyToManyField(to='loans.Owners'),
        ),
    ]
